### ISSUE TITLE
oxi_peaks no longer exists

### ISSUE THREAD

**Issue by lytlemn** [embodied-computation-group/Cardioception#52]
We are excited about implementing this for our research study and tried to get it running for the first time this week. In HRD/task.py oxi_peaks is imported from systole.detection but it seems the newest version of your systole package no longer includes this function. Was there a renaming of this function? Should we be using an older version of systole?

**Comment by LegrandNico** [comment]
Thank you for your message @lytlemn . Yes Cardioception currently install the last version of Systole by default but it should actually use version 0.1.3, you can manually install it using `pip install systole==0.1.3` for now I will make the changes soon on the setup file.
