### ISSUE TITLE
French version

### ISSUE THREAD

**Issue by aliceumons** [embodied-computation-group/Cardioception#55]
Hello, thank you for this very interesting research! Is there a french version of this task?

**Comment by LegrandNico** [comment]
Hi @aliceumons , 

We appreciate your interest in our package. We do not have a French version yet, but if that is something you would be interested in, I can help you create one. 

All we have to do is to translate this function https://github.com/embodied-computation-group/Cardioception/blob/dd4212007edbb382cda24a87a0e1466b06ab5aa4/cardioception/HRD/languages.py#L5-L124 into French, just like we did for the two Danish versions in the same file.

I might start working on it one of these days (I don't know when I will have the time), but if you want to contribute your version in the meantime this will be highly appreciated :thumbsup:

**Comment by aliceumons** [comment]
Thanks for your answer! I can of course contribute to the translation of the function. I will do that in the next few weeks. I will let you know !

**Comment by LegrandNico** [comment]
Closed by #56
