### ISSUE TITLE
Threshold and slope values 

### ISSUE THREAD

**Issue by aliceumons** [embodied-computation-group/Cardioception#57]
Hi Nicolas! How can we obtain the values of the threshold and the slope for HRD task? I can't find them in the HTML reports. Thanks for your help!

**Comment by LegrandNico** [comment]
You can estimate threshold and slope in two ways:
* Using the psi estimates that are updated online during the task. You can find these values in the `EstimatedThreshold` and `EstimatedSlope` columns from the result data frames.
* You can re-estimate the values offline, you can check this example based on PyMC, see [this example](https://embodied-computation-group.github.io/Cardioception/examples/psychophysics/1-psychophysics_subject_level.html#psychophysics-subject-level). We are using this approach most of the time as it allows to drop bad trials.

Also, [this one](https://embodied-computation-group.github.io/Cardioception/examples/templates/HeartRateDiscrimination.html#hrd-template) details some basic analyses from the task data.
